// Copyright  2018 TikalTechnologies.io
// Do not distribute.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/xumak-grid/grid-controller-manager/pkg/client/clientset/versioned/typed/elasticpath/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeElasticpathV1alpha1 struct {
	*testing.Fake
}

func (c *FakeElasticpathV1alpha1) Deployments(namespace string) v1alpha1.DeploymentInterface {
	return &FakeDeployments{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeElasticpathV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
