// Copyright  2018 TikalTechnologies.io
// Do not distribute.

// Code generated by informer-gen. DO NOT EDIT.

package externalversions

import (
	"fmt"

	v1alpha1 "github.com/xumak-grid/grid-controller-manager/pkg/apis/databases/v1alpha1"
	elasticpath_v1alpha1 "github.com/xumak-grid/grid-controller-manager/pkg/apis/elasticpath/v1alpha1"
	hippo_v1alpha1 "github.com/xumak-grid/grid-controller-manager/pkg/apis/hippo/v1alpha1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	cache "k8s.io/client-go/tools/cache"
)

// GenericInformer is type of SharedIndexInformer which will locate and delegate to other
// sharedInformers based on type
type GenericInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() cache.GenericLister
}

type genericInformer struct {
	informer cache.SharedIndexInformer
	resource schema.GroupResource
}

// Informer returns the SharedIndexInformer.
func (f *genericInformer) Informer() cache.SharedIndexInformer {
	return f.informer
}

// Lister returns the GenericLister.
func (f *genericInformer) Lister() cache.GenericLister {
	return cache.NewGenericLister(f.Informer().GetIndexer(), f.resource)
}

// ForResource gives generic access to a shared informer of the matching type
// TODO extend this to unknown resources with a client pool
func (f *sharedInformerFactory) ForResource(resource schema.GroupVersionResource) (GenericInformer, error) {
	switch resource {
	// Group=databases.xumak.io, Version=v1alpha1
	case v1alpha1.SchemeGroupVersion.WithResource("databases"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Databases().V1alpha1().Databases().Informer()}, nil

		// Group=elasticpath.xumak.io, Version=v1alpha1
	case elasticpath_v1alpha1.SchemeGroupVersion.WithResource("deployments"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Elasticpath().V1alpha1().Deployments().Informer()}, nil

		// Group=hippo.xumak.io, Version=v1alpha1
	case hippo_v1alpha1.SchemeGroupVersion.WithResource("hippos"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Hippo().V1alpha1().Hippos().Informer()}, nil

	}

	return nil, fmt.Errorf("no informer found for %v", resource)
}
