// Copyright  2018 TikalTechnologies.io
// Do not distribute.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// DatabaseListerExpansion allows custom methods to be added to
// DatabaseLister.
type DatabaseListerExpansion interface{}

// DatabaseNamespaceListerExpansion allows custom methods to be added to
// DatabaseNamespaceLister.
type DatabaseNamespaceListerExpansion interface{}
