// Copyright  2018 TikalTechnologies.io
// Do not distribute.

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	hippo_v1alpha1 "github.com/xumak-grid/grid-controller-manager/pkg/apis/hippo/v1alpha1"
	versioned "github.com/xumak-grid/grid-controller-manager/pkg/client/clientset/versioned"
	internalinterfaces "github.com/xumak-grid/grid-controller-manager/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/xumak-grid/grid-controller-manager/pkg/client/listers/hippo/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// HippoInformer provides access to a shared informer and lister for
// Hippos.
type HippoInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.HippoLister
}

type hippoInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewHippoInformer constructs a new informer for Hippo type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewHippoInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredHippoInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredHippoInformer constructs a new informer for Hippo type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredHippoInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.HippoV1alpha1().Hippos(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.HippoV1alpha1().Hippos(namespace).Watch(options)
			},
		},
		&hippo_v1alpha1.Hippo{},
		resyncPeriod,
		indexers,
	)
}

func (f *hippoInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredHippoInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *hippoInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&hippo_v1alpha1.Hippo{}, f.defaultInformer)
}

func (f *hippoInformer) Lister() v1alpha1.HippoLister {
	return v1alpha1.NewHippoLister(f.Informer().GetIndexer())
}
