// Copyright  2018 TikalTechnologies.io
// Do not distribute.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// DeploymentListerExpansion allows custom methods to be added to
// DeploymentLister.
type DeploymentListerExpansion interface{}

// DeploymentNamespaceListerExpansion allows custom methods to be added to
// DeploymentNamespaceLister.
type DeploymentNamespaceListerExpansion interface{}
