// Copyright  2018 TikalTechnologies.io
// Do not distribute.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// HippoListerExpansion allows custom methods to be added to
// HippoLister.
type HippoListerExpansion interface{}

// HippoNamespaceListerExpansion allows custom methods to be added to
// HippoNamespaceLister.
type HippoNamespaceListerExpansion interface{}
